/*
 * Copyright 2021 EPAM Systems.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.epam.digital.data.platform.kafkaapi.core.commandhandler;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;

import com.epam.digital.data.platform.kafkaapi.core.commandhandler.util.DmlOperationHandler;
import com.epam.digital.data.platform.kafkaapi.core.commandhandler.util.EntityConverter;
import com.epam.digital.data.platform.kafkaapi.core.config.GenericConfig;
import com.epam.digital.data.platform.kafkaapi.core.config.TestConfiguration;
import com.epam.digital.data.platform.kafkaapi.core.impl.commandhandler.TestEntityWithAutoGeneratedValueCreateCommandHandler;
import com.epam.digital.data.platform.kafkaapi.core.impl.commandhandler.TestEntityWithAutoGeneratedValueDeleteCommandHandler;
import com.epam.digital.data.platform.kafkaapi.core.impl.commandhandler.TestEntityWithAutoGeneratedValueUpdateCommandHandler;
import com.epam.digital.data.platform.kafkaapi.core.impl.model.TestEntityWithAutoGeneratedValue;
import com.epam.digital.data.platform.kafkaapi.core.impl.sequencedata.TestEntityWithAutoGeneratedValueSequenceDataProvider;
import com.epam.digital.data.platform.kafkaapi.core.impl.tabledata.TestEntityWithAutoGeneratedValueTableDataProvider;
import com.epam.digital.data.platform.kafkaapi.core.service.JwtInfoProvider;
import com.epam.digital.data.platform.kafkaapi.core.service.SequenceGenerator;
import com.epam.digital.data.platform.kafkaapi.core.util.DaoTestUtils;
import com.epam.digital.data.platform.kafkaapi.core.util.SecurityUtils;
import com.epam.digital.data.platform.model.core.kafka.Request;
import com.epam.digital.data.platform.model.core.kafka.RequestContext;
import com.epam.digital.data.platform.starter.security.jwt.TokenParser;
import com.nimbusds.jose.JOSEException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

@TestConfiguration
@SpringBootTest(
    classes = {
        TestEntityWithAutoGeneratedValueCreateCommandHandler.class,
        TestEntityWithAutoGeneratedValueUpdateCommandHandler.class,
        TestEntityWithAutoGeneratedValueDeleteCommandHandler.class,
        TestEntityWithAutoGeneratedValueSequenceDataProvider.class,
        SequenceGenerator.class,
        EntityConverter.class,
        TestEntityWithAutoGeneratedValueTableDataProvider.class,
        DmlOperationHandler.class,
        JwtInfoProvider.class,
        TokenParser.class,
        GenericConfig.class
    })
class TestEntityWithAutoGeneratedValueCommandHandlerIT {

  @Autowired
  TestEntityWithAutoGeneratedValueCreateCommandHandler createCommandHandler;
  @Autowired
  TestEntityWithAutoGeneratedValueUpdateCommandHandler updateCommandHandler;
  @Autowired
  TestEntityWithAutoGeneratedValueDeleteCommandHandler deleteCommandHandler;

  TestEntityWithAutoGeneratedValue newTestRecord;
  Request<TestEntityWithAutoGeneratedValue> newTestRequest;
  TestEntityWithAutoGeneratedValue existingTestRecord;
  Request<TestEntityWithAutoGeneratedValue> existingTestRequest;

  @BeforeEach
  void setUp() throws JOSEException {
    newTestRecord = new TestEntityWithAutoGeneratedValue();
    newTestRecord.setPersonFullName("Kurylo Volodymyr");

    existingTestRecord = DaoTestUtils.testEntityWithAutoGeneratedValue();

    newTestRequest = new Request<>(newTestRecord, new RequestContext(),
        SecurityUtils.mockSecurityContext());
    existingTestRequest = new Request<>(existingTestRecord, new RequestContext(),
        SecurityUtils.mockSecurityContext());
  }

  @Test
  @DisplayName("Save new record has no errors on processing")
  void expectNoErrorsWhenSave() {

    Assertions.assertDoesNotThrow(() -> createCommandHandler.save(newTestRequest));
  }

  @Test
  @DisplayName("Update record has no errors on processing")
  void expectNoErrorsWhenUpdate() {
    String updatedName = "Test User";
    existingTestRecord.setPersonFullName(updatedName);

    assertDoesNotThrow(() -> updateCommandHandler.update(existingTestRequest));
  }

  @Test
  @DisplayName("Delete record has no errors on processing")
  void expectNoErrorsWhenDelete() {
    assertDoesNotThrow(() -> deleteCommandHandler.delete(existingTestRequest));
  }
}
