/*
 * Copyright 2021 EPAM Systems.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.epam.digital.data.platform.kafkaapi.core.impl.sequencedata;

import com.epam.digital.data.platform.kafkaapi.core.model.Sequence;
import com.epam.digital.data.platform.kafkaapi.core.service.AbstractSequenceProvider;
import java.util.Map;
import org.springframework.stereotype.Component;

@Component
public class TestEntityWithAutoGeneratedValueSequenceDataProvider extends AbstractSequenceProvider {

  @Override
  public Map<String, Sequence> columnSequence() {
    return Map.ofEntries(
        Map.entry("auto_generated_number",
            new Sequence("test_entity_with_auto_generated_value_auto_generated_number_seq",
                "АА/{dd-MM-yyyy/HH:mm:ss}/{SEQ}")), 
        Map.entry("auto_generated_number2",
            new Sequence("test_entity_with_auto_generated_value_auto_generated_number_seq",
                "АА/{dd-MM-yyyy/HfffH:mm:ss}/{SEQ}")
        )
    );
  }
}
